version: '3.8'

services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app1
    ports:
      - "8080:8080"
    environment:
      - ENV_VARIABLE=value

  service2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8081:8080"
    environment:
      - ENV_VARIABLE=value
